### ISSUE TITLE
方法出处

### ISSUE THREAD

**Issue by DemonWang555** [zzw-create/Communication-efficient-federated-learning-based-on-adaptive-quantization-weights#2]
你好，想麻烦你问一下这个方法是否有出处呢？

**Comment by zzw-create** [comment]
出处放到附件中了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zzw-create/Communication-efficient-federated-learning-based-on-adaptive-quantization-weights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月21日(星期三) 晚上11:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zzw-create/Communication-efficient-federated-learning-based-on-adaptive-quantization-weights] 方法出处 (Issue #2)





 
你好，想麻烦你问一下这个方法是否有出处呢？

**Comment by DemonWang555** [comment]
> 

不好意思，我仔细查找了一下，好像并没有在邮件中找到您所说的附件

**Comment by zzw-create** [comment]
On Maintaining Linear Convergence of Distributed Learning and Optimization Under Limited Communication
如果还是没有的话，你自己下载一下吧，论文名为这个


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zzw-create/Communication-efficient-federated-learning-based-on-adaptive-quantization-weights"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月22日(星期四) 上午9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zzw-create/Communication-efficient-federated-learning-based-on-adaptive-quantization-weights] 方法出处 (Issue #2)





   
不好意思，我仔细查找了一下，好像并没有在邮件中找到您所说的附件

**Comment by DemonWang555** [comment]
> On Maintaining Linear Convergence of Distributed Learning and Optimization Under Limited Communication 如果还是没有的话，你自己下载一下吧，论文名为这个
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zzw-create/Communication-efficient-federated-learning-based-on-adaptive-quantization-weights" ***@***.***&gt;; 发送时间:&nbsp;2022年9月22日(星期四) 上午9:57 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zzw-create/Communication-efficient-federated-learning-based-on-adaptive-quantization-weights] 方法出处 (Issue #2) 不好意思，我仔细查找了一下，好像并没有在邮件中找到您所说的附件 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

十分感谢
